import { useState } from 'react'
import { managers, positions } from '../data/mockPlayers'
import { useDraft } from '../hooks/useDraft'
import { nextDraftDeadline } from '../lib/deadlines'
import Countdown from './Countdown'
import PlayerDetailSheet from './PlayerDetailSheet'

export default function DraftRoom({ onBack }) {
  const [tab, setTab] = useState('NEEDS')
  const [selectedPlayer, setSelectedPlayer] = useState(null)
  const [fallbackDeadline] = useState(() => nextDraftDeadline())
  const { week, players, picks, captains, queue, profile, syncStatus, error, currentManager, complete, draftOpen, queueOpen, canFitRoster, canDraft, draft, chooseCaptain, toggleQueue, moveQueue } = useDraft()
  const deadline = week ? new Date(week.draft_closes_at) : fallbackDeadline
  const allAvailable = players.filter((player) => !picks.some((pick) => String(pick.playerId) === String(player.id)) && (tab === 'NEEDS' ? canFitRoster(player) : tab === 'ALL' || player.position === tab))
  const available = allAvailable.slice(0, 20)
  const picksFor = (manager) => picks.filter((pick) => pick.manager === manager)
  const slotOrder = ['QB', 'RB1', 'RB2', 'WR1', 'WR2', 'TE', 'FLEX']
  const remainingSlots = (manager) => slotOrder.filter((slot) => !picksFor(manager).some((pick) => pick.rosterSlot === slot))
  const needs = remainingSlots(profile?.display_name ?? currentManager)

  return <div className="draft-room">
    <header className="draft-nav"><button onClick={onBack} className="back-button">←</button><div><p className="company">Rivalry Series</p><h1>Week {week?.nfl_week ?? 1} Draft</h1></div><span className="mock-badge">{syncStatus === 'demo' ? 'Prototype · Mock data' : `Supabase · ${syncStatus}`}</span></header>
    <section className="turn-banner"><div><span className="live-pill"><i /> {complete ? 'Draft complete' : draftOpen ? 'On the clock' : 'Draft scheduled'}</span><h2>{complete ? 'Choose your captains' : draftOpen ? `${currentManager}, you’re up.` : 'Week 1 opens September 7.'}</h2><p>{complete ? 'Captains lock at kickoff of the first game.' : draftOpen ? `Pick ${picks.length + 1} of 14 · All selections are final` : `${profile?.display_name ?? 'Manager'}, your live roster is connected and ready.`}</p></div><div><p className="timer-label">{draftOpen ? 'Draft closes' : 'Draft opens Monday · 12:00 AM PT'}</p><Countdown deadline={draftOpen ? deadline : week ? new Date(week.draft_opens_at) : deadline} /></div></section>
    <section className="draft-needs"><div><p className="eyebrow">Your remaining needs</p><strong>{needs.length ? `${needs.length} roster spots left` : 'Roster complete'}</strong></div><div>{slotOrder.map((slot) => <button className={!needs.includes(slot) ? 'filled' : tab === slot.replace(/[12]/g, '') ? 'active' : ''} onClick={() => needs.includes(slot) && setTab(slot === 'FLEX' ? 'NEEDS' : slot.replace(/[12]/g, ''))} key={slot}><span>{!needs.includes(slot) ? '✓' : slot}</span><small>{!needs.includes(slot) ? 'Filled' : slot === 'FLEX' ? 'RB / WR / TE' : `Need ${slot.replace(/[12]/g, '')}`}</small></button>)}</div></section>
    {error && <p className="draft-error" role="alert">{error}</p>}
    <div className="draft-layout">
      <section className="player-board"><div className="board-heading"><div><p className="eyebrow">Player pool</p><h2>{tab === 'NEEDS' ? 'Players you can roster' : tab === 'ALL' ? 'All available players' : `All available ${tab}s`}</h2></div><span>Top {available.length} of {allAvailable.length}</span></div><div className="position-tabs"><button className={tab === 'NEEDS' ? 'active' : ''} onClick={() => setTab('NEEDS')}>For you</button>{positions.map((position) => <button className={tab === position ? 'active' : ''} onClick={() => setTab(position)} key={position}>{position}</button>)}</div>
        <div className="player-list">{available.map((player, rank) => { const fitsRoster = canFitRoster(player); const eligible = canDraft(player); const queued = queue.includes(String(player.id)); const initials = player.name.split(/\s+/).map((part) => part[0]).slice(0, 2).join(''); return <article className={fitsRoster ? 'player-card' : 'player-card roster-ineligible'} role="button" tabIndex="0" onClick={() => setSelectedPlayer(player)} onKeyDown={(event) => { if (event.currentTarget === event.target && (event.key === 'Enter' || event.key === ' ')) setSelectedPlayer(player) }} key={player.id}><span className="rank">#{rank + 1}</span><div className="headshot-wrap"><div className={`position-chip pos-${player.position.toLowerCase()}`}>{initials}</div>{player.headshotUrl && <img className="player-headshot" src={player.headshotUrl} alt={`${player.name} headshot`} loading="lazy" onError={(event) => { event.currentTarget.hidden = true }} />}<span>{player.position}{player.positionRank ? player.positionRank : ''}</span></div><div className="player-info"><h3>{player.name} {player.status !== 'Healthy' && <span className="injury" title={player.injuryNotes || player.status}>!</span>}</h3><p><b>{player.team}</b> · {player.opponent} {player.status !== 'Healthy' && <em>{player.status}</em>}</p><div className="player-metrics"><span><small>2026 avg</small><strong>{player.fantasyAverage == null ? 'No games' : `${player.fantasyAverage.toFixed(1)} pts`}</strong></span><span><small>Week projection</small><strong>{player.projection == null ? 'Not available' : `${Number(player.projection).toFixed(1)} pts`}</strong></span><span><small>Scoring</small><strong>Half PPR</strong></span></div></div><div className="player-actions"><button className={queued ? 'queue-toggle queued' : 'queue-toggle'} onClick={(event) => { event.stopPropagation(); toggleQueue(player.id) }} disabled={!queueOpen}>{queued ? '✓ Queued' : '+ Queue'}</button><button className="draft-player" onClick={(event) => { event.stopPropagation(); draft(player) }} disabled={!eligible}>{eligible ? `Draft ${player.position}` : !fitsRoster ? `${player.position} filled` : !draftOpen ? 'Locked' : `${currentManager}’s turn`}</button></div></article> })}</div>
      </section>
      <aside className="draft-sidebar">
        {managers.map((manager) => { const teamPicks = picksFor(manager); const captainLocked = Boolean(captains[manager]); const isMyRoster = !profile || profile.display_name === manager; return <section className="roster-card" key={manager}><div className="roster-head"><div className={`mini-avatar avatar-${manager.toLowerCase()}`}>{manager[0]}</div><div><span>{manager}’s roster</span><strong>{teamPicks.length}/7 players{captainLocked ? ' · captain locked' : ''}</strong></div></div><div className="roster-slots">{slotOrder.map((slot) => { const pick = teamPicks.find((item) => item.rosterSlot === slot); const player = pick && players.find((item) => String(item.id) === String(pick.playerId)); return player ? <div className="roster-player" key={slot}><span>{slot}</span><strong>{player.name}{pick.isAutoPick ? ' · AUTO' : ''}</strong>{complete && <button className={captains[manager] === player.id ? 'captain active' : 'captain'} disabled={captainLocked || !isMyRoster} title={captainLocked ? 'Captain locked' : isMyRoster ? 'Lock this captain' : `${manager} chooses this captain`} onClick={() => chooseCaptain(manager, player.id)}>★</button>}</div> : <div className="empty-slot needed" key={slot}><b>{slot}</b><span>{slot === 'FLEX' ? 'RB, WR, or TE needed' : `${slot.replace(/[12]/g, '')} needed`}</span></div>})}</div></section> })}
        <section className="queue-card"><div className="queue-heading"><div><p className="eyebrow">Private auto-pick queue</p><strong>{queue.length} players</strong></div><span>Only you can see this</span></div>{queue.length === 0 ? <p className="empty-history">Add players from the board. At the deadline, your first legal choice is used.</p> : <div className="queue-list">{queue.map((playerId, index) => { const player = players.find((item) => String(item.id) === playerId); if (!player || picks.some((pick) => String(pick.playerId) === playerId)) return null; return <div className="queue-player" key={playerId}><b>{index + 1}</b><span>{player.name}<small>{player.position} · {player.team}</small></span><div><button onClick={() => moveQueue(playerId, -1)} disabled={!queueOpen || index === 0}>↑</button><button onClick={() => moveQueue(playerId, 1)} disabled={!queueOpen || index === queue.length - 1}>↓</button><button onClick={() => toggleQueue(playerId)} disabled={!queueOpen}>×</button></div></div> })}</div>}<p className="queue-fallback">No legal queue choice? You receive the fifth-best legal player.</p></section>
        <section className="history-card"><p className="eyebrow">Draft history</p>{picks.length === 0 ? <span className="empty-history">The first pick is waiting.</span> : [...picks].reverse().slice(0, 5).map((pick, index) => { const player = players.find((item) => item.id === pick.playerId); return <div className="history-pick" key={player.id}><b>{picks.length - index}</b><span><strong>{player.name}</strong>{pick.manager} · {player.position}</span></div> })}</section>
      </aside>
    </div>
    <p className="data-credit">Player data: Sleeper · Schedule data: nflverse</p>
    {selectedPlayer && <PlayerDetailSheet player={selectedPlayer} fitsRoster={canFitRoster(selectedPlayer)} eligible={canDraft(selectedPlayer)} queued={queue.includes(String(selectedPlayer.id))} queueOpen={queueOpen} currentManager={currentManager} onClose={() => setSelectedPlayer(null)} onQueue={() => toggleQueue(selectedPlayer.id)} onDraft={() => draft(selectedPlayer)} />}
  </div>
}
