import { useEffect } from 'react'

const formatKickoff = (value) => value ? new Intl.DateTimeFormat('en-US', { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : 'Kickoff TBD'
const initials = (name) => name.split(/\s+/).map((part) => part[0]).slice(0, 2).join('')

export default function PlayerDetailSheet({ player, fitsRoster, eligible, queued, queueOpen, currentManager, onClose, onQueue, onDraft }) {
  useEffect(() => {
    const closeOnEscape = (event) => { if (event.key === 'Escape') onClose() }
    document.addEventListener('keydown', closeOnEscape)
    document.body.classList.add('sheet-open')
    return () => { document.removeEventListener('keydown', closeOnEscape); document.body.classList.remove('sheet-open') }
  }, [onClose])

  const draftLabel = eligible ? `Draft ${player.position}` : !fitsRoster ? `${player.position} spot filled` : `${currentManager}'s turn`
  return <div className="player-sheet-layer"><button className="player-sheet-scrim" type="button" onClick={onClose} aria-label="Close player details" /><section className="player-sheet" role="dialog" aria-modal="true" aria-labelledby="player-sheet-name"><header><span>Player details</span><button type="button" onClick={onClose} aria-label="Close">×</button></header><div className="player-sheet-hero"><div className={`player-sheet-photo pos-${player.position.toLowerCase()}`}><span>{initials(player.name)}</span>{player.headshotUrl && <img src={player.headshotUrl} alt={`${player.name} headshot`} onError={(event) => { event.currentTarget.hidden = true }} />}</div><div><p>{player.position}{player.positionRank ? player.positionRank : ''} · {player.team}</p><h2 id="player-sheet-name">{player.name}</h2><strong>{player.opponent}</strong><small>{formatKickoff(player.gameStartsAt)}</small></div></div><div className="player-sheet-fit"><span className={fitsRoster ? 'fit' : 'filled'}>{fitsRoster ? '✓ Fits your roster' : `Your ${player.position} spot is filled`}</span><p>{fitsRoster ? player.position === 'QB' ? 'Eligible for your open quarterback slot.' : 'Eligible for a primary roster slot or FLEX.' : `Browse this player here, but you cannot draft another ${player.position} unless a FLEX opening applies.`}</p></div><div className="player-detail-grid"><article><small>Week projection</small><strong>{player.projection == null ? 'Not available' : `${Number(player.projection).toFixed(1)} pts`}</strong></article><article><small>Season average</small><strong>{player.fantasyAverage == null ? 'No games yet' : `${player.fantasyAverage.toFixed(1)} pts`}</strong></article><article><small>Position rank</small><strong>{player.positionRank ? `${player.position}${player.positionRank}` : 'Not ranked'}</strong></article><article><small>Format</small><strong>Half PPR</strong></article></div><section className="player-form"><div><p className="eyebrow">Recent fantasy scores</p><span>{player.gamesPlayed} games</span></div>{player.recentScores?.length ? <div>{player.recentScores.map((game) => <article key={game.week}><span>Week {game.week}</span><strong>{game.points.toFixed(1)} pts</strong></article>)}</div> : <p>No completed 2026 games yet.</p>}</section><section className={`player-injury-detail ${player.status === 'Healthy' ? 'healthy' : ''}`}><span>{player.status === 'Healthy' ? '✓' : '!'}</span><div><strong>{player.status}</strong><p>{player.injuryNotes || (player.status === 'Healthy' ? 'No current injury designation.' : 'Monitor the official game status before drafting.')}</p></div></section><footer><button className={queued ? 'queued' : ''} type="button" disabled={!queueOpen} onClick={onQueue}>{queued ? '✓ In queue' : '+ Add to queue'}</button><button type="button" disabled={!eligible} onClick={onDraft}>{draftLabel}</button></footer></section></div>
}
